package vu.lt.mybatis.model;

import java.util.List;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.CUSTOMER_NAME
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.CUSTOMER_SURNAME
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    private String customerSurname;

    private List<Package> packagesToSend;

    private List<Package> packagesToReceive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @return the value of PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @param id the value for PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.CUSTOMER_NAME
     *
     * @return the value of PUBLIC.CUSTOMER.CUSTOMER_NAME
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.CUSTOMER_NAME
     *
     * @param customerName the value for PUBLIC.CUSTOMER.CUSTOMER_NAME
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.CUSTOMER_SURNAME
     *
     * @return the value of PUBLIC.CUSTOMER.CUSTOMER_SURNAME
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public String getCustomerSurname() {
        return customerSurname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.CUSTOMER_SURNAME
     *
     * @param customerSurname the value for PUBLIC.CUSTOMER.CUSTOMER_SURNAME
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public void setCustomerSurname(String customerSurname) {
        this.customerSurname = customerSurname;
    }
}