package vu.lt.mybatis.model;

import java.util.List;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.EMPLOYEE_NAME
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.EMPLOYEE_SURNAME
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    private String employeeSurname;

    private List<Package> deliveries;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @return the value of PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    public void setDeliveries(List<Package> deliveries){this.deliveries = deliveries;}
    public  List<Package> getDeliveries() {return this.deliveries;}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @param id the value for PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.EMPLOYEE_NAME
     *
     * @return the value of PUBLIC.EMPLOYEE.EMPLOYEE_NAME
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.EMPLOYEE_NAME
     *
     * @param employeeName the value for PUBLIC.EMPLOYEE.EMPLOYEE_NAME
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.EMPLOYEE_SURNAME
     *
     * @return the value of PUBLIC.EMPLOYEE.EMPLOYEE_SURNAME
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public String getEmployeeSurname() {
        return employeeSurname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.EMPLOYEE_SURNAME
     *
     * @param employeeSurname the value for PUBLIC.EMPLOYEE.EMPLOYEE_SURNAME
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public void setEmployeeSurname(String employeeSurname) {
        this.employeeSurname = employeeSurname;
    }
}