package vu.lt.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

public class Package {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PACKAGE.ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PACKAGE.PACKAGE_SHIP_ADDRESS
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    private String packageShipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PACKAGE.PACKAGE_WEIGHT
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    private Double packageWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PACKAGE.RECEIVER_ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    private Integer receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PACKAGE.SENDER_ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    private Integer senderId;

    @Getter
    @Setter
    public Customer receiver;

    @Getter
    @Setter
    public Customer sender;

    @Getter
    @Setter
    public List<Employee> couriers;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PACKAGE.ID
     *
     * @return the value of PUBLIC.PACKAGE.ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PACKAGE.ID
     *
     * @param id the value for PUBLIC.PACKAGE.ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PACKAGE.PACKAGE_SHIP_ADDRESS
     *
     * @return the value of PUBLIC.PACKAGE.PACKAGE_SHIP_ADDRESS
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public String getPackageShipAddress() {
        return packageShipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PACKAGE.PACKAGE_SHIP_ADDRESS
     *
     * @param packageShipAddress the value for PUBLIC.PACKAGE.PACKAGE_SHIP_ADDRESS
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public void setPackageShipAddress(String packageShipAddress) {
        this.packageShipAddress = packageShipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PACKAGE.PACKAGE_WEIGHT
     *
     * @return the value of PUBLIC.PACKAGE.PACKAGE_WEIGHT
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public Double getPackageWeight() {
        return packageWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PACKAGE.PACKAGE_WEIGHT
     *
     * @param packageWeight the value for PUBLIC.PACKAGE.PACKAGE_WEIGHT
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public void setPackageWeight(Double packageWeight) {
        this.packageWeight = packageWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PACKAGE.RECEIVER_ID
     *
     * @return the value of PUBLIC.PACKAGE.RECEIVER_ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public Integer getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PACKAGE.RECEIVER_ID
     *
     * @param receiverId the value for PUBLIC.PACKAGE.RECEIVER_ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PACKAGE.SENDER_ID
     *
     * @return the value of PUBLIC.PACKAGE.SENDER_ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public Integer getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PACKAGE.SENDER_ID
     *
     * @param senderId the value for PUBLIC.PACKAGE.SENDER_ID
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    public void setSenderId(Integer senderId) {
        this.senderId = senderId;
    }
}