package vu.lt.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Employee;
import vu.lt.mybatis.model.Package;

@Mapper
public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE
     *
     * @mbg.generated Sun May 08 21:57:40 EEST 2022
     */
    int updateByPrimaryKey(Employee record);

    List<Package> selectDeliveriesForEmployee(Integer id);

    int insertNewDeliveryForEmployee(@Param("employeeId")Integer employeeId, @Param("packageId")Integer packageId);

    int deleteDeliveryForEmployee(@Param("employeeId")Integer employeeId, @Param("packageId")Integer packageId);
}